version: "3.8"
services:
  strapi:
    build: .
    environment:
      NODE_ENV: production
      STRAPI_VERSION: 4.0.0
      SEED_DB: "true"
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - .:/srv/app
    ports:
      - "${HOST_PORT:-1337}:1337"
    depends_on:
      - postgres
    command: "strapi start"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
